# **Beginning with TensorFlow: An Easy Guide to the Basics**
# Completed the first exercise

On 2023-09-28 12:44:41 IST, I completed the first exercise by successfully implementing the following tasks:

1. Created a vector, scalar, matrix, and tensor with values of my choosing using `tf.constant()`.
2. Found the shape, rank, and size of the tensors created in 1.
3. Created two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiplied the two tensors created in 3 using matrix multiplication.
5. Multiplied the two tensors created in 3 using dot product.
6. Created a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Found the min and max values of the tensor created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` and squeezed it to change the shape to `[224, 224, 3]`.
9. Created a tensor with shape `[10]` using my own choice of values and found the index which has the maximum value.
10. One-hot encoded the tensor created in 9.

I am able to perform these tasks using the TensorFlow library in Python.

In [1]:
import tensorflow as tf

## 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().


In [2]:
# Scaler
scaler = tf.constant([2.])
scaler

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.], dtype=float32)>

In [3]:
# Vector
vector = tf.constant([2., 4])
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 4.], dtype=float32)>

In [6]:
# Tensor
tensor = tf.constant([[[7, 8, 9],
                       [2, 3, 4],
                       [6, 7, 8]],
                     [[3, 5, 8],
                       [2, 4, 1],
                       [7, 6, 4]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[7, 8, 9],
        [2, 3, 4],
        [6, 7, 8]],

       [[3, 5, 8],
        [2, 4, 1],
        [7, 6, 4]]], dtype=int32)>

In [7]:
# Changing dtype from tf.int32 to tf.float32
tensor = tf.cast(tensor, dtype = tf.float32)
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[7., 8., 9.],
        [2., 3., 4.],
        [6., 7., 8.]],

       [[3., 5., 8.],
        [2., 4., 1.],
        [7., 6., 4.]]], dtype=float32)>

## 2. Find the shape, rank and size of the tensors you created in 1.


In [13]:
# Make a function to print shape, rank, dtype and size of the tensor
def tensor_details(tensors):
  print(f"The Shape of the tensor is: {tensors.shape}")
  print(f"The Data Type of the tensor is: {tensors.dtype}")
  print(f"The Rank of the tensor is: {tensors.ndim}")
  print(f"The Size of the tensor is: {tf.size(tensors)}")

In [14]:
# Print the details of the scaler
tensor_details(tensors = scaler)

The Shape of the tensor is: (1,)
The Data Type of the tensor is: <dtype: 'float32'>
The Rank of the tensor is: 1
The Size of the tensor is: 1


In [15]:
# Print the details of the vector
tensor_details(tensors = vector)

The Shape of the tensor is: (2,)
The Data Type of the tensor is: <dtype: 'float32'>
The Rank of the tensor is: 1
The Size of the tensor is: 2


In [16]:
# Print the details of the tensor
tensor_details(tensors = tensor)

The Shape of the tensor is: (2, 3, 3)
The Data Type of the tensor is: <dtype: 'float32'>
The Rank of the tensor is: 3
The Size of the tensor is: 18


## 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].


In [27]:
# Create the first random tensor
rand_tensor_1 = tf.random.uniform(shape = (5, 300), minval = 0, maxval =1, dtype = tf.float32)
rand_tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.871006  , 0.26772833, 0.70052826, ..., 0.9958092 , 0.88451374,
        0.02774656],
       [0.29573095, 0.08307981, 0.8463013 , ..., 0.2965592 , 0.42236185,
        0.23221707],
       [0.9413271 , 0.01625109, 0.8064767 , ..., 0.7248441 , 0.04778063,
        0.02783906],
       [0.45789182, 0.48169374, 0.05352521, ..., 0.67139375, 0.7018634 ,
        0.0206666 ],
       [0.09435797, 0.23158312, 0.22509229, ..., 0.86319685, 0.4334606 ,
        0.84026873]], dtype=float32)>

In [26]:
# Create the second random tensor
rand_tensor_2 = tf.random.uniform(shape = (5, 300), minval = 0, maxval = 1, dtype = tf.float32)
rand_tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.00645912, 0.09539831, 0.07274544, ..., 0.85791993, 0.5680046 ,
        0.8968018 ],
       [0.8961171 , 0.04036999, 0.08538961, ..., 0.4917549 , 0.8526765 ,
        0.4926566 ],
       [0.9022001 , 0.38847113, 0.44612038, ..., 0.6606715 , 0.4494294 ,
        0.58377814],
       [0.9203582 , 0.01808488, 0.09637952, ..., 0.9622711 , 0.97690845,
        0.71614766],
       [0.20296896, 0.7281723 , 0.6341667 , ..., 0.23219562, 0.7219757 ,
        0.6741427 ]], dtype=float32)>

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [30]:
# Multiple the two random tensor
mul_rand_tensor = tf.matmul(rand_tensor_1, tf.transpose(rand_tensor_2))
mul_rand_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.63771 , 77.7502  , 72.53029 , 83.67258 , 74.8227  ],
       [78.96401 , 75.97806 , 71.37254 , 78.209625, 77.09809 ],
       [75.382675, 76.170334, 69.441696, 75.67501 , 71.28725 ],
       [80.51748 , 78.83559 , 73.13079 , 79.80719 , 77.455475],
       [79.722145, 77.0036  , 72.33737 , 77.51207 , 73.51101 ]],
      dtype=float32)>

In [34]:
# Details of the multiple of the two random tensors
tensor_details(mul_rand_tensor)

The Shape of the tensor is: (5, 5)
The Data Type of the tensor is: <dtype: 'float32'>
The Rank of the tensor is: 2
The Size of the tensor is: 25


## 5. Multiply the two tensors you created in 3 using dot product.


In [33]:
# Dot product of the two random tensors
dot_product_rand_tensor = tf.tensordot(rand_tensor_1, tf.transpose(rand_tensor_2), axes = 1)
dot_product_rand_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.63771 , 77.7502  , 72.53029 , 83.67258 , 74.8227  ],
       [78.96401 , 75.97806 , 71.37254 , 78.209625, 77.09809 ],
       [75.382675, 76.170334, 69.441696, 75.67501 , 71.28725 ],
       [80.51748 , 78.83559 , 73.13079 , 79.80719 , 77.455475],
       [79.722145, 77.0036  , 72.33737 , 77.51207 , 73.51101 ]],
      dtype=float32)>

In [35]:
# Details of the dot product of the two random tensors
tensor_details(dot_product_rand_tensor)

The Shape of the tensor is: (5, 5)
The Data Type of the tensor is: <dtype: 'float32'>
The Rank of the tensor is: 2
The Size of the tensor is: 25


In [36]:
# Check if both multiple and dot product tensors are same
dot_product_rand_tensor == mul_rand_tensor

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

## 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [37]:
# Create the third random tensor
rand_tensor_3 = tf.random.uniform(shape = (224, 224, 3), minval = 0, maxval = 1, dtype = tf.float32)
rand_tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.96018720e-01, 1.99381828e-01, 1.18622780e-01],
        [3.22146177e-01, 6.69598579e-04, 3.89103532e-01],
        [8.30721617e-01, 2.23304391e-01, 7.83316135e-01],
        ...,
        [3.49993706e-02, 6.16197586e-02, 4.60074544e-01],
        [8.59300017e-01, 6.70737505e-01, 6.26915932e-01],
        [6.20012283e-02, 1.60748124e-01, 2.92175293e-01]],

       [[2.47467518e-01, 3.04933906e-01, 3.96587849e-02],
        [7.17518568e-01, 9.02341366e-01, 8.07777643e-01],
        [8.70510578e-01, 9.35254812e-01, 4.13454413e-01],
        ...,
        [2.03850985e-01, 4.49869633e-01, 3.36335778e-01],
        [4.33019042e-01, 3.36093903e-02, 4.14172411e-02],
        [9.21145439e-01, 6.52278662e-02, 4.62229848e-01]],

       [[9.45632815e-01, 9.84209299e-01, 7.95394182e-01],
        [4.97862458e-01, 1.80742145e-01, 1.71226144e-01],
        [5.31246662e-01, 3.02328825e-01, 6.34706736e-01],
        ...,
        [4.06601429e-01, 5.92159

In [38]:
# Details of the third random tensor
tensor_details(rand_tensor_3)

The Shape of the tensor is: (224, 224, 3)
The Data Type of the tensor is: <dtype: 'float32'>
The Rank of the tensor is: 3
The Size of the tensor is: 150528


## 7. Find the min and max values of the tensor you created in 6.


In [67]:
# Min vale and max value of the third random tensor
print(f"The Minimum Value in third randoom tensor is {tf.reduce_min(rand_tensor_3)}")
print(f"The Maximum Value in third random tensor is {tf.reduce_max(rand_tensor_3)}")

The Minimum Value in third randoom tensor is 1.1086463928222656e-05
The Maximum Value in third random tensor is 0.999983549118042


## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].


In [75]:
# Create the fourth random tensor
rand_tensor_4 = tf.random.normal(shape = (1, 224, 224, 3))
print(f"Shape of the fourth random tensor before squeezing: {rand_tensor_4.shape} ")

Shape of the fourth random tensor before squeezing: (1, 224, 224, 3) 


In [77]:
# Squeeze the fourth random tensor from shape = (1, 224, 224, 3) --> shape = (224, 224, 3)
rand_tensor_4 = tf.squeeze(rand_tensor_4)
print(f"Shape of the fourth random tensor after squeezing: {rand_tensor_4.shape} ")

Shape of the fourth random tensor after squeezing: (224, 224, 3) 


## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.


In [80]:
# Create a tensor with shape [10]
tensor_10_shape = tf.constant([5, 7, 4, 6, 10, 3, 5, 6, 4, 3], dtype = tf.float32)
tensor_10_shape.shape

TensorShape([10])

In [89]:
# Find the index which has the maximum value.
print(f"The index with maximum value in the above tensor is: {tf.argmax(tensor_10_shape).numpy()} ")

The index with maximum value in the above tensor is: 4 


## 10. One-hot encode the tensor you created in 9.


In [96]:
# One-Hot Encode the tensor with the shape: [10]
tensor_10_shape = tf.cast(tensor_10_shape, dtype = tf.int32)
tf.one_hot(tensor_10_shape, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>